name: Build

on:
  push:
  pull_request:
  schedule:
  - cron: "*/10 0 * * *"

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master branch
      uses: actions/checkout@v2
    - name: echo
      shell: bash
      run: echo foobar
